### ISSUE TITLE
missing function "protected T getItemFromProvider()" in class de.itemis.base.GenericListActivity (Android)

### ISSUE THREAD

**Issue by tschoenbein** [applause/applause#14]
Hi,

this bug happens when I create a new Applause Project with Android as Target Platform.

The "missing" function is included in the example project itemisApp but not in new Projects (new - APPLause Project - Target plattform Android).

**Comment by HBehrens** [comment]
should be fixed with 588c60ec6d8d4539a88312742b40c615f6a28236
Please re-open if this error still occurs.
