### ISSUE TITLE
(Generator-Android) Bug in ListActivities.xpt --> NullPointerException 

### ISSUE THREAD

**Issue by tschoenbein** [applause/applause#15]
Der folgende Applause-Code führt zu folgenden Java-Code:

`detailsview BlogDetails(BlogItem item) {`
    **title= item.title**
    `header {
        title= item.title
        details= item.description
    }
    section {   
        cell Default {
            text= "Open in Browser"
            action= item.link
        }}}`

public class BlogDetails extends DetailsActivity<BlogItem> {

```
BlogItem item;

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setTitle(item.getTitle());

    item = getItemFromProvider();

    setHeaderTitle(item.getTitle());
```

ZUr Laufzeit wird dann eine NullPointerException geworfen da item noch nicht initialisiert wurde.

**Comment by HBehrens** [comment]
fixed with 384f8a4d3ce5d1dcaafb4fbd6256a3b8500a922b
