### ISSUE TITLE
no viable alternative at character 'ª'	

### ISSUE THREAD

**Issue by RefuX** [applause/applause#20]
Just cloned the project and opened up in Eclipse.
I get 31 errors which are all for basically the same thing:
Description Resource    Path    Location    Type
no viable alternative at character 'ª' Activities.xpt  /org.applause.lang.generator.android/src/templates  Unknown Xtend/Xpand Problem

**Comment by peterfriese** [comment]
This is an encoding related problem. Try to configure your workspace to use ISO-8859-1.

**Comment by RefuX** [comment]
Thanks :)
