### ISSUE TITLE
model project produces error markers: "Project X is missing required Java project Y"

### ISSUE THREAD

**Issue by HBehrens** [applause/applause#8]
Description Resource    Path    Location    Type
Project 'itemisApp' is missing required Java project: 'itemisApp.gae'   itemisApp       Build path  Build Path Problem
Project 'itemisApp' is missing required Java project: 'itemisApp.iPhone'    itemisApp       Build path  Build Path Problem
Project 'itemisApp' is missing required Java project: 'itemisApp.wp7'   itemisApp       Build path  Build Path Problem
The project cannot be built until build path errors are resolved    itemisApp       Unknown Java Problem

When refreshing the workspace I got these errors.

**Comment by peterfriese** [comment]
Seems this has been fixed by mficner@e22067c in #17. Reopen if it re-appears.
